---
author: Niek Schoorl
baseurl: /
description: Creaties in glas door Niek Schoorl
locale: nl
title: Glas Studio Roderveld
url: https://glasstudioroderveld.nl

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "assets/img"
    values:
      image: true

exclude:
  - "Gemfile"
  
