---
baseurl: /glasstudioroderveld.nl/
url: https://peachey-schoorl.com
title: Glas Studio Roderveld

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

exclude:
  - "vendor/"
  - "Gemfile"
  - "*.json"
  - "*.lock"
