---
baseurl: /
url: https://glasstudioroderveld.nl
title: Glas Studio Roderveld
author: Niek Schoorl
locale: nl

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

exclude:
  - "Gemfile"
  
